In [151]:
import pandas as pd
from sklearn.metrics import classification_report,f1_score

In [152]:
old_to_new_mapping = {
    "Advanced LLM Prompting": "Advanced LLM Prompting",
    "Classical Models": "Forecasting with Classical Models",
    "Enhanced User Intent Comprehension with LLMs": "LLM-based User Intent Extraction",
    "LLM Agent Training & Alignment": "LLM Fine-Tuning, Training & Alignment",
    "LLM Context Management": "LLM-based Context Management",
    "LLM Results Evaluation": "Evaluating LLM Results",
    "LLM based Multimodal Generative Prompting": "LLM-based Multimodal Generative Prompting",
    "LLM based Planning, Iterative Optimizations and ReAct, or Reasoning, Think Step by step, XoT":
        "LLM-based Planning, XoT, ReAct, or Reasoning",
    "Model Abstraction Pattern": "Model Abstraction",
    "Modular LLM Agent Architectures": "Agent Architecture",
    "None": "None",
    "Preprocessing Text and Numerical Data": "Preprocessing Text and Numerical Data",
    "Reliable, Transparent, & Augmented LLMs":
        "Enabling Reliability, Explainability, or Robustness",
    "Retrieval Augmented Generation(RAG) Optimization for LLMs":
        "Retrieval Augmented Generation(RAG)",
    "Structured Output & Formatting for LLMs":
        "Performing Structured Output & Formatting for LLMs",
    "Tool Use for LLMs": "Using Tools with LLMs"
}

In [153]:
def format_cluster_id(id):
    names = id.split("/")
    return names[-2]+"/"+names[-1]

def format_pattern_name(name):
    return name.strip().split(":")[0]

def map_old_to_new(old_name):
    old_name = old_name.strip()
    return old_to_new_mapping.get(old_name, old_name)

In [154]:
labeled_data = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/data/datasets/labeled_data.csv')
labeled_data_map = [format_cluster_id(i['file']) for i in labeled_data[labeled_data['verified']==True].to_dict(orient='records')]
pattern_name_map = {format_cluster_id(i['file']): i['verified_pattern'] for i in labeled_data.to_dict(orient='records')}
def is_verified(cluster_id):
    formatted_id = format_cluster_id(cluster_id)
    return formatted_id in labeled_data_map

In [155]:
def show_report(y_true, y_pred):
    report = classification_report(y_true, y_pred,labels=sorted(set(y_true)), zero_division=0, output_dict=True)
    df = pd.DataFrame(report).transpose()
    return df

In [156]:
pattern_name_map

{'3DOD_thesis/cluster_0.py': 'LLM-based Multimodal Generative Prompting',
 '3DOD_thesis/cluster_1.py': 'none',
 '3DOD_thesis/cluster_10.py': 'LLM-based Multimodal Generative Prompting',
 '3DOD_thesis/cluster_2.py': nan,
 '3DOD_thesis/cluster_3.py': 'Preprocessing Text and Numerical Data',
 '3DOD_thesis/cluster_4.py': 'none',
 '3DOD_thesis/cluster_5.py': 'none',
 '3DOD_thesis/cluster_6.py': nan,
 '3DOD_thesis/cluster_7.py': nan,
 '3DOD_thesis/cluster_8.py': 'LLM-based Multimodal Generative Prompting',
 '3DOD_thesis/cluster_9.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_0.py': 'MLOps',
 'AIlice/cluster_1.py': 'Agent Architecture',
 'AIlice/cluster_10.py': 'Model Abstraction',
 'AIlice/cluster_11.py': 'Model Abstraction',
 'AIlice/cluster_12.py': nan,
 'AIlice/cluster_13.py': nan,
 'AIlice/cluster_14.py': 'none',
 'AIlice/cluster_15.py': 'none',
 'AIlice/cluster_16.py': 'Model Abstraction',
 'AIlice/cluster_17.py': 'Using Tools with LLMs',
 'AIlice/cluster_18.py': nan,
 'AIlice/cluster_19.py': 'none',
 'AIlice/cluster_2.py': 'Model Abstraction',
 'AIlice/cluster_20.py': nan,
 'AIlice/cluster_21.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_22.py': nan,
 'AIlice/cluster_23.py': 'LLM Fine-Tuning, Training & Alignment',
 'AIlice/cluster_24.py': 'Using Tools with LLMs',
 'AIlice/cluster_25.py': 'Using Tools with LLMs',
 'AIlice/cluster_26.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_27.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_28.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_29.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_3.py': 'Agent Architecture',
 'AIlice/cluster_30.py': 'Using Tools with LLMs',
 'AIlice/cluster_31.py': nan,
 'AIlice/cluster_32.py': 'Evaluating LLM Results',
 'AIlice/cluster_33.py': 'Using Tools with LLMs',
 'AIlice/cluster_34.py': 'Agent Architecture',
 'AIlice/cluster_35.py': 'Using Tools with LLMs',
 'AIlice/cluster_36.py': 'Preprocessing Text and Numerical Data',
 'AIlice/cluster_37.py': 'none',
 'AIlice/cluster_38.py': 'LLM-based Multimodal Generative Prompting',
 'AIlice/cluster_4.py': 'Using Tools with LLMs',
 'AIlice/cluster_5.py': 'Retrieval Augmented Generation(RAG)',
 'AIlice/cluster_6.py': 'Model Abstraction',
 'AIlice/cluster_7.py': 'Using Tools with LLMs',
 'AIlice/cluster_8.py': 'Agent Architecture',
 'AIlice/cluster_9.py': 'LLM-based Multimodal Generative Prompting',
 'AgentBench/cluster_0.py': nan,
 'AgentBench/cluster_1.py': nan,
 'AgentBench/cluster_10.py': 'Using Tools with LLMs',
 'AgentBench/cluster_11.py': 'Using Tools with LLMs',
 'AgentBench/cluster_12.py': nan,
 'AgentBench/cluster_13.py': 'MLOps',
 'AgentBench/cluster_14.py': nan,
 'AgentBench/cluster_15.py': nan,
 'AgentBench/cluster_16.py': nan,
 'AgentBench/cluster_17.py': nan,
 'AgentBench/cluster_18.py': 'LLM-based Planning, XoT, ReAct, or Reasoning',
 'AgentBench/cluster_19.py': 'LLM Fine-Tuning, Training & Alignment',
 'AgentBench/cluster_2.py': nan,
 'AgentBench/cluster_20.py': 'Using Tools with LLMs',
 'AgentBench/cluster_3.py': 'MLOps',
 'AgentBench/cluster_4.py': 'Evaluating LLM Results',
 'AgentBench/cluster_5.py': 'LLM-based User Intent Extraction',
 'AgentBench/cluster_6.py': nan,
 'AgentBench/cluster_7.py': 'Using Tools with LLMs',
 'AgentBench/cluster_8.py': 'LLM-based User Intent Extraction',
 'AgentBench/cluster_9.py': 'Preprocessing Text and Numerical Data',
 'ArxivDigest/cluster_0.py': 'Retrieval Augmented Generation(RAG)',
 'ArxivDigest/cluster_1.py': nan,
 'ArxivDigest/cluster_2.py': 'Preprocessing Text and Numerical Data',
 'ArxivDigest/cluster_3.py': nan,
 'Automatic_Speech_Recognition/cluster_0.py': 'Preprocessing Text and Numerical Data',
 'Automatic_Speech_Recognition/cluster_1.py': 'Forecasting with Classical Models',
 'Automatic_Speech_Recognition/cluster_10.py': 'LLM-based Multimodal Generative Prompting',
 'Automatic_Speech_Recognition/cluster_11.py': nan,
 'Automatic_Speech_Recognition/cluster_12.py': 'Forecasting with Classical Models',
 'Automatic_Speech_Recognition/cluster_13.py': nan,
 'Automatic_Speech_Recognition/cluster_14.py': 'Forecasting with Classical Models',
 'Automatic_Speech_Recognition/cluster_15.py': nan,
 'Automatic_Speech_Recognition/cluster_16.py': 'LLM-based Multimodal Generative Prompting',
 'Automatic_Speech_Recognition/cluster_17.py': 'Enabling Reliability, Explainability, or Robustness',
 'Automatic_Speech_Recognition/cluster_18.py': 'Preprocessing Text and Numerical Data',
 'Automatic_Speech_Recognition/cluster_2.py': nan,
 'Automatic_Speech_Recognition/cluster_3.py': nan,
 'Automatic_Speech_Recognition/cluster_4.py': 'Preprocessing Text and Numerical Data',
 'Automatic_Speech_Recognition/cluster_5.py': 'Forecasting with Classical Models',
 'Automatic_Speech_Recognition/cluster_6.py': 'Preprocessing Text and Numerical Data',
 'Automatic_Speech_Recognition/cluster_7.py': 'Preprocessing Text and Numerical Data',
 'Automatic_Speech_Recognition/cluster_8.py': nan,
 'Automatic_Speech_Recognition/cluster_9.py': 'none',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_0.py': 'Forecasting with Classical Models',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_1.py': 'Forecasting with Classical Models',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_2.py': 'LLM Fine-Tuning, Training & Alignment',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_3.py': nan,
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_4.py': 'Forecasting with Classical Models',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_5.py': 'Using Tools with LLMs',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_6.py': 'LLM-based Planning, XoT, ReAct, or Reasoning',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_7.py': 'Forecasting with Classical Models',
 'Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/cluster_8.py': 'LLM-based Planning, XoT, ReAct, or Reasoning',
 'BruteForceAI/cluster_0.py': nan,
 'BruteForceAI/cluster_1.py': nan,
 'BruteForceAI/cluster_2.py': nan,
 'BruteForceAI/cluster_3.py': nan,
 'BruteForceAI/cluster_4.py': nan,
 'CAAFE/cluster_0.py': nan,
 'CAAFE/cluster_1.py': 'LLM-based Planning, XoT, ReAct, or Reasoning',
 'CAAFE/cluster_2.py': 'Preprocessing Text and Numerical Data',
 'CAAFE/cluster_3.py': 'none',
 'CAAFE/cluster_4.py': nan,
 'CAAFE/cluster_5.py': nan,
 'CAAFE/cluster_6.py': nan,
 'CAAFE/cluster_7.py': nan,
 'CAAFE/cluster_8.py': 'Preprocessing Text and Numerical Data',
 'ChatSim/cluster_0.py': nan,
 'ChatSim/cluster_1.py': nan,
 'ChatSim/cluster_10.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_100.py': nan,
 'ChatSim/cluster_101.py': nan,
 'ChatSim/cluster_102.py': nan,
 'ChatSim/cluster_103.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_104.py': nan,
 'ChatSim/cluster_105.py': nan,
 'ChatSim/cluster_106.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_107.py': 'Preprocessing Text and Numerical Data',
 'ChatSim/cluster_108.py': nan,
 'ChatSim/cluster_109.py': nan,
 'ChatSim/cluster_11.py': nan,
 'ChatSim/cluster_110.py': nan,
 'ChatSim/cluster_111.py': nan,
 'ChatSim/cluster_112.py': nan,
 'ChatSim/cluster_113.py': nan,
 'ChatSim/cluster_114.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_115.py': nan,
 'ChatSim/cluster_116.py': nan,
 'ChatSim/cluster_117.py': nan,
 'ChatSim/cluster_118.py': nan,
 'ChatSim/cluster_119.py': nan,
 'ChatSim/cluster_12.py': 'none',
 'ChatSim/cluster_120.py': nan,
 'ChatSim/cluster_121.py': nan,
 'ChatSim/cluster_122.py': nan,
 'ChatSim/cluster_123.py': nan,
 'ChatSim/cluster_124.py': 'Enabling Reliability, Explainability, or Robustness',
 'ChatSim/cluster_125.py': nan,
 'ChatSim/cluster_126.py': nan,
 'ChatSim/cluster_127.py': nan,
 'ChatSim/cluster_128.py': nan,
 'ChatSim/cluster_129.py': nan,
 'ChatSim/cluster_13.py': nan,
 'ChatSim/cluster_130.py': nan,
 'ChatSim/cluster_131.py': nan,
 'ChatSim/cluster_132.py': nan,
 'ChatSim/cluster_133.py': nan,
 'ChatSim/cluster_134.py': nan,
 'ChatSim/cluster_135.py': nan,
 'ChatSim/cluster_136.py': nan,
 'ChatSim/cluster_137.py': nan,
 'ChatSim/cluster_138.py': nan,
 'ChatSim/cluster_139.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_14.py': nan,
 'ChatSim/cluster_140.py': nan,
 'ChatSim/cluster_141.py': nan,
 'ChatSim/cluster_142.py': 'MLOps',
 'ChatSim/cluster_143.py': 'none',
 'ChatSim/cluster_144.py': nan,
 'ChatSim/cluster_145.py': nan,
 'ChatSim/cluster_146.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_147.py': nan,
 'ChatSim/cluster_148.py': nan,
 'ChatSim/cluster_149.py': nan,
 'ChatSim/cluster_15.py': nan,
 'ChatSim/cluster_150.py': nan,
 'ChatSim/cluster_151.py': nan,
 'ChatSim/cluster_152.py': nan,
 'ChatSim/cluster_153.py': nan,
 'ChatSim/cluster_154.py': nan,
 'ChatSim/cluster_155.py': nan,
 'ChatSim/cluster_156.py': nan,
 'ChatSim/cluster_157.py': nan,
 'ChatSim/cluster_158.py': nan,
 'ChatSim/cluster_159.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_16.py': nan,
 'ChatSim/cluster_160.py': nan,
 'ChatSim/cluster_161.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_162.py': nan,
 'ChatSim/cluster_17.py': nan,
 'ChatSim/cluster_18.py': nan,
 'ChatSim/cluster_19.py': nan,
 'ChatSim/cluster_2.py': nan,
 'ChatSim/cluster_20.py': nan,
 'ChatSim/cluster_21.py': nan,
 'ChatSim/cluster_22.py': nan,
 'ChatSim/cluster_23.py': nan,
 'ChatSim/cluster_24.py': nan,
 'ChatSim/cluster_25.py': nan,
 'ChatSim/cluster_26.py': nan,
 'ChatSim/cluster_27.py': nan,
 'ChatSim/cluster_28.py': nan,
 'ChatSim/cluster_29.py': nan,
 'ChatSim/cluster_3.py': nan,
 'ChatSim/cluster_30.py': nan,
 'ChatSim/cluster_31.py': nan,
 'ChatSim/cluster_32.py': nan,
 'ChatSim/cluster_33.py': nan,
 'ChatSim/cluster_34.py': nan,
 'ChatSim/cluster_35.py': nan,
 'ChatSim/cluster_36.py': nan,
 'ChatSim/cluster_37.py': nan,
 'ChatSim/cluster_38.py': nan,
 'ChatSim/cluster_39.py': nan,
 'ChatSim/cluster_4.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_40.py': nan,
 'ChatSim/cluster_41.py': 'none',
 'ChatSim/cluster_42.py': nan,
 'ChatSim/cluster_43.py': nan,
 'ChatSim/cluster_44.py': nan,
 'ChatSim/cluster_45.py': nan,
 'ChatSim/cluster_46.py': nan,
 'ChatSim/cluster_47.py': nan,
 'ChatSim/cluster_48.py': nan,
 'ChatSim/cluster_49.py': nan,
 'ChatSim/cluster_5.py': nan,
 'ChatSim/cluster_50.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_51.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_52.py': nan,
 'ChatSim/cluster_53.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_54.py': nan,
 'ChatSim/cluster_55.py': nan,
 'ChatSim/cluster_56.py': nan,
 'ChatSim/cluster_57.py': nan,
 'ChatSim/cluster_58.py': nan,
 'ChatSim/cluster_59.py': nan,
 'ChatSim/cluster_6.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_60.py': nan,
 'ChatSim/cluster_61.py': nan,
 'ChatSim/cluster_62.py': nan,
 'ChatSim/cluster_63.py': 'none',
 'ChatSim/cluster_64.py': nan,
 'ChatSim/cluster_65.py': nan,
 'ChatSim/cluster_66.py': nan,
 'ChatSim/cluster_67.py': 'LLM-based Multimodal Generative Prompting',
 'ChatSim/cluster_68.py': nan,
 'ChatSim/cluster_69.py': nan,
 'ChatSim/cluster_7.py': nan,
 'ChatSim/cluster_70.py': nan,
 'ChatSim/cluster_71.py': nan,
 'ChatSim/cluster_72.py': nan,
 'ChatSim/cluster_73.py': nan,
 'ChatSim/cluster_74.py': nan,
 'ChatSim/cluster_75.py': nan,
 'ChatSim/cluster_76.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_77.py': nan,
 'ChatSim/cluster_78.py': nan,
 'ChatSim/cluster_79.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_8.py': 'Evaluating LLM Results',
 'ChatSim/cluster_80.py': nan,
 'ChatSim/cluster_81.py': nan,
 'ChatSim/cluster_82.py': nan,
 'ChatSim/cluster_83.py': nan,
 'ChatSim/cluster_84.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_85.py': nan,
 'ChatSim/cluster_86.py': nan,
 'ChatSim/cluster_87.py': nan,
 'ChatSim/cluster_88.py': nan,
 'ChatSim/cluster_89.py': nan,
 'ChatSim/cluster_9.py': nan,
 'ChatSim/cluster_90.py': nan,
 'ChatSim/cluster_91.py': nan,
 'ChatSim/cluster_92.py': 'Evaluating LLM Results',
 'ChatSim/cluster_93.py': nan,
 'ChatSim/cluster_94.py': nan,
 'ChatSim/cluster_95.py': nan,
 'ChatSim/cluster_96.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_97.py': 'Forecasting with Classical Models',
 'ChatSim/cluster_98.py': nan,
 'ChatSim/cluster_99.py': nan,
 'Copilot-Agent-365/cluster_0.py': nan,
 'Copilot-Agent-365/cluster_1.py': 'Retrieval Augmented Generation(RAG)',
 'Copilot-Agent-365/cluster_2.py': 'Using Tools with LLMs',
 'Copilot-Agent-365/cluster_3.py': nan,
 'Copilot-Agent-365/cluster_4.py': 'MLOps',
 'CyberScraper-2077/cluster_0.py': nan,
 'CyberScraper-2077/cluster_1.py': nan,
 'CyberScraper-2077/cluster_2.py': nan,
 'CyberScraper-2077/cluster_3.py': nan,
 'CyberScraper-2077/cluster_4.py': nan,
 'CyberScraper-2077/cluster_5.py': 'none',
 'CyberScraper-2077/cluster_6.py': nan,
 'CyberScraper-2077/cluster_7.py': 'Model Abstraction',
 'CyberScraper-2077/cluster_8.py': nan,
 'CyberScraper-2077/cluster_9.py': nan,
 'DI-sheep/cluster_0.py': nan,
 'DI-sheep/cluster_1.py': nan,
 'DI-sheep/cluster_2.py': nan,
 'DLTA-AI/cluster_0.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_1.py': nan,
 'DLTA-AI/cluster_10.py': nan,
 'DLTA-AI/cluster_100.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_101.py': nan,
 'DLTA-AI/cluster_102.py': nan,
 'DLTA-AI/cluster_103.py': nan,
 'DLTA-AI/cluster_104.py': nan,
 'DLTA-AI/cluster_105.py': nan,
 'DLTA-AI/cluster_106.py': nan,
 'DLTA-AI/cluster_107.py': nan,
 'DLTA-AI/cluster_108.py': nan,
 'DLTA-AI/cluster_109.py': 'MLOps',
 'DLTA-AI/cluster_11.py': nan,
 'DLTA-AI/cluster_110.py': 'Forecasting with Classical Models',
 'DLTA-AI/cluster_111.py': nan,
 'DLTA-AI/cluster_112.py': 'Preprocessing Text and Numerical Data',
 'DLTA-AI/cluster_113.py': 'Preprocessing Text and Numerical Data',
 'DLTA-AI/cluster_114.py': nan,
 'DLTA-AI/cluster_115.py': nan,
 'DLTA-AI/cluster_116.py': 'Forecasting with Classical Models',
 'DLTA-AI/cluster_117.py': nan,
 'DLTA-AI/cluster_118.py': nan,
 'DLTA-AI/cluster_119.py': nan,
 'DLTA-AI/cluster_12.py': nan,
 'DLTA-AI/cluster_120.py': nan,
 'DLTA-AI/cluster_121.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_122.py': nan,
 'DLTA-AI/cluster_123.py': nan,
 'DLTA-AI/cluster_124.py': nan,
 'DLTA-AI/cluster_125.py': nan,
 'DLTA-AI/cluster_126.py': nan,
 'DLTA-AI/cluster_13.py': nan,
 'DLTA-AI/cluster_14.py': nan,
 'DLTA-AI/cluster_15.py': nan,
 'DLTA-AI/cluster_16.py': 'MLOps',
 'DLTA-AI/cluster_17.py': nan,
 'DLTA-AI/cluster_18.py': 'LLM Fine-Tuning, Training & Alignment',
 'DLTA-AI/cluster_19.py': nan,
 'DLTA-AI/cluster_2.py': 'none',
 'DLTA-AI/cluster_20.py': nan,
 'DLTA-AI/cluster_21.py': 'Evaluating LLM Results',
 'DLTA-AI/cluster_22.py': nan,
 'DLTA-AI/cluster_23.py': nan,
 'DLTA-AI/cluster_24.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_25.py': nan,
 'DLTA-AI/cluster_26.py': 'none',
 'DLTA-AI/cluster_27.py': nan,
 'DLTA-AI/cluster_28.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_29.py': nan,
 'DLTA-AI/cluster_31.py': 'Forecasting with Classical Models',
 'DLTA-AI/cluster_32.py': 'Evaluating LLM Results',
 'DLTA-AI/cluster_33.py': 'Forecasting with Classical Models',
 'DLTA-AI/cluster_34.py': nan,
 'DLTA-AI/cluster_35.py': nan,
 'DLTA-AI/cluster_36.py': 'Preprocessing Text and Numerical Data',
 'DLTA-AI/cluster_37.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_38.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_39.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_4.py': nan,
 'DLTA-AI/cluster_40.py': 'Preprocessing Text and Numerical Data',
 'DLTA-AI/cluster_41.py': nan,
 'DLTA-AI/cluster_42.py': nan,
 'DLTA-AI/cluster_43.py': nan,
 'DLTA-AI/cluster_44.py': nan,
 'DLTA-AI/cluster_45.py': nan,
 'DLTA-AI/cluster_46.py': nan,
 'DLTA-AI/cluster_47.py': 'none',
 'DLTA-AI/cluster_48.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_49.py': nan,
 'DLTA-AI/cluster_5.py': nan,
 'DLTA-AI/cluster_50.py': nan,
 'DLTA-AI/cluster_51.py': nan,
 'DLTA-AI/cluster_52.py': nan,
 'DLTA-AI/cluster_54.py': nan,
 'DLTA-AI/cluster_55.py': nan,
 'DLTA-AI/cluster_56.py': nan,
 'DLTA-AI/cluster_57.py': nan,
 'DLTA-AI/cluster_58.py': nan,
 'DLTA-AI/cluster_59.py': nan,
 'DLTA-AI/cluster_6.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_60.py': nan,
 'DLTA-AI/cluster_61.py': nan,
 'DLTA-AI/cluster_62.py': 'Forecasting with Classical Models',
 'DLTA-AI/cluster_63.py': nan,
 'DLTA-AI/cluster_64.py': nan,
 'DLTA-AI/cluster_65.py': 'Preprocessing Text and Numerical Data',
 'DLTA-AI/cluster_66.py': nan,
 'DLTA-AI/cluster_67.py': nan,
 'DLTA-AI/cluster_68.py': nan,
 'DLTA-AI/cluster_69.py': nan,
 'DLTA-AI/cluster_70.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_71.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_72.py': nan,
 'DLTA-AI/cluster_73.py': nan,
 'DLTA-AI/cluster_74.py': nan,
 'DLTA-AI/cluster_75.py': nan,
 'DLTA-AI/cluster_76.py': nan,
 'DLTA-AI/cluster_77.py': nan,
 'DLTA-AI/cluster_78.py': nan,
 'DLTA-AI/cluster_79.py': nan,
 'DLTA-AI/cluster_80.py': nan,
 'DLTA-AI/cluster_81.py': nan,
 'DLTA-AI/cluster_82.py': nan,
 'DLTA-AI/cluster_83.py': nan,
 'DLTA-AI/cluster_85.py': nan,
 'DLTA-AI/cluster_86.py': nan,
 'DLTA-AI/cluster_88.py': nan,
 'DLTA-AI/cluster_89.py': nan,
 'DLTA-AI/cluster_90.py': nan,
 'DLTA-AI/cluster_91.py': 'LLM-based Multimodal Generative Prompting',
 'DLTA-AI/cluster_93.py': nan,
 'DLTA-AI/cluster_97.py': nan,
 'DRL-Pytorch/cluster_0.py': nan,
 'DRL-Pytorch/cluster_1.py': nan,
 'DRL-Pytorch/cluster_2.py': nan,
 'DRL-Pytorch/cluster_3.py': nan,
 'DRL-Pytorch/cluster_4.py': nan,
 'DRL-Pytorch/cluster_5.py': 'Forecasting with Classical Models',
 'DRL-Pytorch/cluster_6.py': 'Forecasting with Classical Models',
 'DeepLearning-IDS/cluster_1.py': nan,
 'DeepLearning-IDS/cluster_2.py': nan,
 'EvoAgentX/cluster_0.py': nan,
 'EvoAgentX/cluster_1.py': 'Retrieval Augmented Generation(RAG)',
 'EvoAgentX/cluster_10.py': 'Evaluating LLM Results',
 'EvoAgentX/cluster_11.py': nan,
 'EvoAgentX/cluster_12.py': 'none',
 'EvoAgentX/cluster_13.py': 'Evaluating LLM Results',
 'EvoAgentX/cluster_14.py': nan,
 'EvoAgentX/cluster_15.py': nan,
 'EvoAgentX/cluster_16.py': 'Using Tools with LLMs',
 'EvoAgentX/cluster_17.py': 'none',
 'EvoAgentX/cluster_19.py': nan,
 'EvoAgentX/cluster_2.py': nan,
 'EvoAgentX/cluster_20.py': nan,
 'EvoAgentX/cluster_21.py': nan,
 'EvoAgentX/cluster_22.py': nan,
 'EvoAgentX/cluster_23.py': 'MLOps',
 'EvoAgentX/cluster_24.py': nan,
 'EvoAgentX/cluster_27.py': nan,
 'EvoAgentX/cluster_28.py': nan,
 'EvoAgentX/cluster_29.py': nan,
 'EvoAgentX/cluster_3.py': nan,
 'EvoAgentX/cluster_30.py': nan,
 'EvoAgentX/cluster_31.py': nan,
 'EvoAgentX/cluster_32.py': 'Evaluating LLM Results',
 'EvoAgentX/cluster_33.py': nan,
 'EvoAgentX/cluster_35.py': nan,
 'EvoAgentX/cluster_38.py': nan,
 'EvoAgentX/cluster_39.py': nan,
 'EvoAgentX/cluster_40.py': nan,
 'EvoAgentX/cluster_41.py': nan,
 'EvoAgentX/cluster_47.py': 'Advanced LLM Prompting',
 'EvoAgentX/cluster_48.py': 'Advanced LLM Prompting',
 'EvoAgentX/cluster_49.py': nan,
 'EvoAgentX/cluster_51.py': nan,
 'EvoAgentX/cluster_52.py': 'Model Abstraction',
 'EvoAgentX/cluster_53.py': nan,
 'EvoAgentX/cluster_54.py': 'Advanced LLM Prompting',
 'EvoAgentX/cluster_55.py': 'Model Abstraction',
 'EvoAgentX/cluster_58.py': 'Preprocessing Text and Numerical Data',
 'EvoAgentX/cluster_59.py': 'Evaluating LLM Results',
 'EvoAgentX/cluster_60.py': 'Agent Architecture',
 'EvoAgentX/cluster_63.py': 'Advanced LLM Prompting',
 'EvoAgentX/cluster_64.py': nan,
 'EvoAgentX/cluster_65.py': 'Agent Architecture',

### Process evolution files

#### Step 00

In [157]:
step_00_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/evolution/step 00.csv')
step_00_df.head()

,community_id,forecasted_pattern
0,https://github.com/HasinthakaPiyumal/AI-Patter...,Tool Use for LLMs: 0.8412
1,https://github.com/HasinthakaPiyumal/AI-Patter...,Tool Use for LLMs: 0.8873
2,https://github.com/HasinthakaPiyumal/AI-Patter...,"LLM based Planning, Iterative Optimizations an..."
3,https://github.com/HasinthakaPiyumal/AI-Patter...,Integrating External Knlowladge with LLM: 0.46...
4,https://github.com/HasinthakaPiyumal/AI-Patter...,Tool Use for LLMs: 0.6573\nLLM based Multimoda...

In [158]:
step_00_df['community_id'] = step_00_df['community_id'].apply(format_cluster_id)
step_00_df['forecasted_pattern'] = step_00_df['forecasted_pattern'].apply(format_pattern_name)
step_00_df['forecasted_pattern'] = step_00_df['forecasted_pattern'].apply(map_old_to_new)
step_00_df['true_pattern'] = step_00_df['community_id'].apply(lambda x: pattern_name_map.get(x, ""))
step_00_df=step_00_df[step_00_df['community_id'].apply(is_verified)]

In [159]:
show_report(step_00_df['true_pattern'], step_00_df['forecasted_pattern'])

,precision,recall,f1-score,support
Advanced LLM Prompting,0.200000,0.214286,0.206897,14.0
Agent Architecture,0.000000,0.000000,0.000000,20.0
"Enabling Reliability, Explainability, or Robustness",0.066667,0.142857,0.090909,7.0
Evaluating LLM Results,0.111111,0.055556,0.074074,18.0
Forecasting with Classical Models,0.000000,0.000000,0.000000,63.0
"LLM Fine-Tuning, Training & Alignment",0.076923,0.750000,0.139535,4.0
LLM-based Context Management,0.000000,0.000000,0.000000,1.0
LLM-based Multimodal Generative Prompting,0.500000,0.520833,0.510204,48.0
"LLM-based Planning, XoT, ReAct, or Reasoning",0.094340,0.416667,0.153846,12.0
LLM-based User Intent Extraction,0.000000,0.000000,0.000000,8.0
MLOps,0.000000,0.000000,0.000000,15.0
Model Abstraction,0.000000,0.000000,0.000000,20.0
Preprocessing Text and Numerical Data,0.000000,0.000000,0.000000,46.0
Retrieval Augmented Generation(RAG),0.379310,0.392857,0.385965,28.0
Using Tools with LLMs,0.136000,0.548387,0.217949,31.0
none,0.000000,0.000000,0.000000,61.0
micro avg,0.193548,0.166667,0.179104,396.0
macro avg,0.097772,0.190090,0.111211,396.0
weighted avg,0.115008,0.166667,0.124555,396.0

In [160]:
step_01_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/evolution/step 01.csv')
step_01_df.head()

                                        community_id forecasted_pattern
0  https://github.com/HasinthakaPiyumal/AI-Patter...  Tool Use for LLMs
1  https://github.com/HasinthakaPiyumal/AI-Patter...  Tool Use for LLMs
2  https://github.com/HasinthakaPiyumal/AI-Patter...  Tool Use for LLMs
3  https://github.com/HasinthakaPiyumal/AI-Patter...  Tool Use for LLMs
4  https://github.com/HasinthakaPiyumal/AI-Patter...  Tool Use for LLMs

In [161]:
step_01_df['community_id'] = step_01_df['community_id'].apply(format_cluster_id)
step_01_df['forecasted_pattern'] = step_01_df['forecasted_pattern'].apply(map_old_to_new)
step_01_df['true_pattern'] = step_01_df['community_id'].apply(lambda x: pattern_name_map.get(x, ""))
step_01_df=step_01_df[step_01_df['community_id'].apply(is_verified)]

In [162]:
show_report(step_01_df['true_pattern'], step_01_df['forecasted_pattern'])

,precision,recall,f1-score,support
Advanced LLM Prompting,0.000000,0.000000,0.000000,14.0
Agent Architecture,0.727273,0.800000,0.761905,20.0
"Enabling Reliability, Explainability, or Robustness",0.000000,0.000000,0.000000,8.0
Evaluating LLM Results,0.823529,0.777778,0.800000,18.0
Forecasting with Classical Models,0.782609,0.843750,0.812030,64.0
"LLM Fine-Tuning, Training & Alignment",0.000000,0.000000,0.000000,4.0
LLM-based Context Management,0.000000,0.000000,0.000000,1.0
LLM-based Multimodal Generative Prompting,0.864865,0.615385,0.719101,52.0
"LLM-based Planning, XoT, ReAct, or Reasoning",0.000000,0.000000,0.000000,12.0
LLM-based User Intent Extraction,0.000000,0.000000,0.000000,8.0
MLOps,0.000000,0.000000,0.000000,18.0
Model Abstraction,0.680000,0.850000,0.755556,20.0
Preprocessing Text and Numerical Data,0.705882,0.705882,0.705882,51.0
Retrieval Augmented Generation(RAG),0.800000,0.714286,0.754717,28.0
Using Tools with LLMs,0.604651,0.838710,0.702703,31.0
none,0.000000,0.000000,0.000000,64.0
micro avg,0.743945,0.520581,0.612536,413.0
macro avg,0.374301,0.384112,0.375743,413.0
weighted avg,0.521000,0.520581,0.515807,413.0

In [163]:
step_02_df.head()

,verified_pattern,file,avg_threshold_class,threshold_class,without_threshold_class,second_level_model_class_lr,second_level_model_class_rr,community_id,forecasted_pattern,true_pattern
0,none,https://github.com/HasinthakaPiyumal/AI-Patter...,none,none,none,none,none,AIlice/cluster_15.py,none,none
1,LLM-based Multimodal Generative Prompting,https://github.com/HasinthakaPiyumal/AI-Patter...,none,none,none,none,none,AIlice/cluster_26.py,none,LLM-based Multimodal Generative Prompting
2,LLM-based Multimodal Generative Prompting,https://github.com/HasinthakaPiyumal/AI-Patter...,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting,AIlice/cluster_29.py,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting
3,Retrieval Augmented Generation(RAG),https://github.com/HasinthakaPiyumal/AI-Patter...,Retrieval Augmented Generation(RAG),Retrieval Augmented Generation(RAG),Retrieval Augmented Generation(RAG),Retrieval Augmented Generation(RAG),Retrieval Augmented Generation(RAG),ArxivDigest/cluster_0.py,Retrieval Augmented Generation(RAG),Retrieval Augmented Generation(RAG)
4,Preprocessing Text and Numerical Data,https://github.com/HasinthakaPiyumal/AI-Patter...,Preprocessing Text and Numerical Data,Preprocessing Text and Numerical Data,Preprocessing Text and Numerical Data,Using Tools with LLMs,Preprocessing Text and Numerical Data,ArxivDigest/cluster_2.py,Using Tools with LLMs,Preprocessing Text and Numerical Data

In [164]:
step_02_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/src/stages/pattern_classification/models/metrics/1769073937.3141153/ensemble_classification_predictions.csv')
step_02_df.head()
step_02_df['community_id'] = step_02_df['file'].apply(format_cluster_id)
step_02_df['forecasted_pattern'] = step_02_df['second_level_model_class_lr'].apply(map_old_to_new)
step_02_df['true_pattern'] = step_02_df['community_id'].apply(lambda x: pattern_name_map.get(x, ""))
step_02_df=step_02_df[step_02_df['community_id'].apply(is_verified)]
show_report(step_02_df['true_pattern'], step_02_df['forecasted_pattern'])

,precision,recall,f1-score,support
Agent Architecture,0.466667,0.350000,0.400000,20.000000
Forecasting with Classical Models,0.767857,0.671875,0.716667,64.000000
LLM-based Context Management,0.000000,0.000000,0.000000,1.000000
LLM-based Multimodal Generative Prompting,0.649123,0.711538,0.678899,52.000000
MLOps,0.000000,0.000000,0.000000,18.000000
Model Abstraction,0.454545,0.500000,0.476190,20.000000
Preprocessing Text and Numerical Data,0.490196,0.490196,0.490196,51.000000
Retrieval Augmented Generation(RAG),0.500000,0.571429,0.533333,28.000000
Using Tools with LLMs,0.324324,0.387097,0.352941,31.000000
none,0.303797,0.375000,0.335664,64.000000
accuracy,0.498567,0.498567,0.498567,0.498567
macro avg,0.395651,0.405713,0.398389,349.000000
weighted avg,0.486586,0.498567,0.490115,349.000000

In [165]:
step_03_df = pd.read_csv('/home/hasinthaka/Documents/Projects/AI/Pattern Mining/pipeline/ensemble_classification_predictions.csv')
step_03_df.head()

,file,true_label,weighted_pred
0,https://github.com/HasinthakaPiyumal/AI-Patter...,LLM-based Multimodal Generative Prompting,none
1,https://github.com/HasinthakaPiyumal/AI-Patter...,none,LLM-based Multimodal Generative Prompting
2,https://github.com/HasinthakaPiyumal/AI-Patter...,LLM-based Multimodal Generative Prompting,LLM-based Multimodal Generative Prompting
3,https://github.com/HasinthakaPiyumal/AI-Patter...,Preprocessing Text and Numerical Data,Preprocessing Text and Numerical Data
4,https://github.com/HasinthakaPiyumal/AI-Patter...,none,LLM-based Multimodal Generative Prompting

In [166]:
step_03_df['community_id'] = step_03_df['file'].apply(format_cluster_id)
step_03_df['forecasted_pattern'] = step_03_df['weighted_pred'].apply(map_old_to_new)
step_03_df['true_pattern'] = step_03_df['community_id'].apply(lambda x: pattern_name_map.get(x, ""))
step_03_df=step_03_df[step_03_df['community_id'].apply(is_verified)]

In [167]:
show_report(step_03_df['true_pattern'], step_03_df['forecasted_pattern'])

,precision,recall,f1-score,support
Agent Architecture,0.615385,0.400000,0.484848,20.000000
Forecasting with Classical Models,0.694444,0.781250,0.735294,64.000000
LLM-based Multimodal Generative Prompting,0.633333,0.730769,0.678571,52.000000
Model Abstraction,0.523810,0.550000,0.536585,20.000000
Preprocessing Text and Numerical Data,0.574468,0.529412,0.551020,51.000000
Retrieval Augmented Generation(RAG),0.620690,0.642857,0.631579,28.000000
Using Tools with LLMs,0.320000,0.258065,0.285714,31.000000
none,0.428571,0.421875,0.425197,64.000000
accuracy,0.566667,0.566667,0.566667,0.566667
macro avg,0.551338,0.539278,0.541101,330.000000
weighted avg,0.558144,0.566667,0.559482,330.000000

In [168]:
show_report(step_00_df['true_pattern'], step_00_df['forecasted_pattern'])

,precision,recall,f1-score,support
Advanced LLM Prompting,0.200000,0.214286,0.206897,14.0
Agent Architecture,0.000000,0.000000,0.000000,20.0
"Enabling Reliability, Explainability, or Robustness",0.066667,0.142857,0.090909,7.0
Evaluating LLM Results,0.111111,0.055556,0.074074,18.0
Forecasting with Classical Models,0.000000,0.000000,0.000000,63.0
"LLM Fine-Tuning, Training & Alignment",0.076923,0.750000,0.139535,4.0
LLM-based Context Management,0.000000,0.000000,0.000000,1.0
LLM-based Multimodal Generative Prompting,0.500000,0.520833,0.510204,48.0
"LLM-based Planning, XoT, ReAct, or Reasoning",0.094340,0.416667,0.153846,12.0
LLM-based User Intent Extraction,0.000000,0.000000,0.000000,8.0
MLOps,0.000000,0.000000,0.000000,15.0
Model Abstraction,0.000000,0.000000,0.000000,20.0
Preprocessing Text and Numerical Data,0.000000,0.000000,0.000000,46.0
Retrieval Augmented Generation(RAG),0.379310,0.392857,0.385965,28.0
Using Tools with LLMs,0.136000,0.548387,0.217949,31.0
none,0.000000,0.000000,0.000000,61.0
micro avg,0.193548,0.166667,0.179104,396.0
macro avg,0.097772,0.190090,0.111211,396.0
weighted avg,0.115008,0.166667,0.124555,396.0

In [169]:
show_report(step_01_df['true_pattern'], step_01_df['forecasted_pattern'])

,precision,recall,f1-score,support
Advanced LLM Prompting,0.000000,0.000000,0.000000,14.0
Agent Architecture,0.727273,0.800000,0.761905,20.0
"Enabling Reliability, Explainability, or Robustness",0.000000,0.000000,0.000000,8.0
Evaluating LLM Results,0.823529,0.777778,0.800000,18.0
Forecasting with Classical Models,0.782609,0.843750,0.812030,64.0
"LLM Fine-Tuning, Training & Alignment",0.000000,0.000000,0.000000,4.0
LLM-based Context Management,0.000000,0.000000,0.000000,1.0
LLM-based Multimodal Generative Prompting,0.864865,0.615385,0.719101,52.0
"LLM-based Planning, XoT, ReAct, or Reasoning",0.000000,0.000000,0.000000,12.0
LLM-based User Intent Extraction,0.000000,0.000000,0.000000,8.0
MLOps,0.000000,0.000000,0.000000,18.0
Model Abstraction,0.680000,0.850000,0.755556,20.0
Preprocessing Text and Numerical Data,0.705882,0.705882,0.705882,51.0
Retrieval Augmented Generation(RAG),0.800000,0.714286,0.754717,28.0
Using Tools with LLMs,0.604651,0.838710,0.702703,31.0
none,0.000000,0.000000,0.000000,64.0
micro avg,0.743945,0.520581,0.612536,413.0
macro avg,0.374301,0.384112,0.375743,413.0
weighted avg,0.521000,0.520581,0.515807,413.0

In [170]:
show_report(step_02_df['true_pattern'], step_02_df['forecasted_pattern'])

,precision,recall,f1-score,support
Agent Architecture,0.466667,0.350000,0.400000,20.000000
Forecasting with Classical Models,0.767857,0.671875,0.716667,64.000000
LLM-based Context Management,0.000000,0.000000,0.000000,1.000000
LLM-based Multimodal Generative Prompting,0.649123,0.711538,0.678899,52.000000
MLOps,0.000000,0.000000,0.000000,18.000000
Model Abstraction,0.454545,0.500000,0.476190,20.000000
Preprocessing Text and Numerical Data,0.490196,0.490196,0.490196,51.000000
Retrieval Augmented Generation(RAG),0.500000,0.571429,0.533333,28.000000
Using Tools with LLMs,0.324324,0.387097,0.352941,31.000000
none,0.303797,0.375000,0.335664,64.000000
accuracy,0.498567,0.498567,0.498567,0.498567
macro avg,0.395651,0.405713,0.398389,349.000000
weighted avg,0.486586,0.498567,0.490115,349.000000

In [171]:
show_report(step_03_df['true_pattern'], step_03_df['forecasted_pattern'])

,precision,recall,f1-score,support
Agent Architecture,0.615385,0.400000,0.484848,20.000000
Forecasting with Classical Models,0.694444,0.781250,0.735294,64.000000
LLM-based Multimodal Generative Prompting,0.633333,0.730769,0.678571,52.000000
Model Abstraction,0.523810,0.550000,0.536585,20.000000
Preprocessing Text and Numerical Data,0.574468,0.529412,0.551020,51.000000
Retrieval Augmented Generation(RAG),0.620690,0.642857,0.631579,28.000000
Using Tools with LLMs,0.320000,0.258065,0.285714,31.000000
none,0.428571,0.421875,0.425197,64.000000
accuracy,0.566667,0.566667,0.566667,0.566667
macro avg,0.551338,0.539278,0.541101,330.000000
weighted avg,0.558144,0.566667,0.559482,330.000000

In [172]:
# # ✅ 1) make index name consistent
# step_00_df.index.name = "pattern_class"
# step_01_df.index.name = "pattern_class"
# step_02_df.index.name = "pattern_class"
# step_03_df.index.name = "pattern_class"

# ✅ 2) convert index -> column (so you can select it)
# step_00_df = step_00_df.reset_index()
# step_01_df = step_01_df.reset_index()
# step_02_df = step_02_df.reset_index()
# step_03_df = step_03_df.reset_index()

# ✅ 3) add step column
step_00_df["step"] = "1"
step_01_df["step"] = "2"
step_02_df["step"] = "3"
step_03_df["step"] = "4"

# # ✅ 4) keep only needed columns
cols = ["step", "community_id", "true_pattern", "forecasted_pattern"]

step_00_df = step_00_df[cols]
step_01_df = step_01_df[cols]
step_02_df = step_02_df[cols]
step_03_df = step_03_df[cols]

# ✅ (optional) combine all steps
final_df = pd.concat([step_00_df, step_01_df, step_02_df, step_03_df], ignore_index=True)
final_df.to_csv("../evolution/evolution_final_results.csv", index=False)

In [173]:
print(step_00_df.columns.tolist())

['step', 'community_id', 'true_pattern', 'forecasted_pattern']

In [174]:
result_df_01

,step,pattern_class,precision,recall,f1-score
0,1,Advanced LLM Prompting,0.200000,0.214286,0.206897
1,1,Agent Architecture,0.000000,0.000000,0.000000
2,1,"Enabling Reliability, Explainability, or Robus...",0.066667,0.142857,0.090909
3,1,Evaluating LLM Results,0.111111,0.055556,0.074074
4,1,Forecasting with Classical Models,0.000000,0.000000,0.000000
5,1,"LLM Fine-Tuning, Training & Alignment",0.076923,0.750000,0.139535
6,1,LLM-based Context Management,0.000000,0.000000,0.000000
7,1,LLM-based Multimodal Generative Prompting,0.500000,0.520833,0.510204
8,1,"LLM-based Planning, XoT, ReAct, or Reasoning",0.094340,0.416667,0.153846
9,1,LLM-based User Intent Extraction,0.000000,0.000000,0.000000
10,1,MLOps,0.000000,0.000000,0.000000
11,1,Model Abstraction,0.000000,0.000000,0.000000
12,1,Preprocessing Text and Numerical Data,0.000000,0.000000,0.000000
13,1,Retrieval Augmented Generation(RAG),0.379310,0.392857,0.385965
14,1,Using Tools with LLMs,0.136000,0.548387,0.217949
15,1,none,0.000000,0.000000,0.000000
16,1,all,0.097772,0.190090,0.111211

In [175]:
result_df_01 = show_report(step_00_df['true_pattern'], step_00_df['forecasted_pattern'])
result_df_02 = show_report(step_01_df['true_pattern'], step_01_df['forecasted_pattern'])
result_df_03 = show_report(step_02_df['true_pattern'], step_02_df['forecasted_pattern'])
result_df_04 = show_report(step_03_df['true_pattern'], step_03_df['forecasted_pattern'])

result_df_01 = result_df_01.drop(index=['accuracy','micro avg','weighted avg'],errors='ignore')
result_df_02 = result_df_02.drop(index=['accuracy','micro avg','weighted avg'],errors='ignore')
result_df_03 = result_df_03.drop(index=['accuracy','micro avg','weighted avg'],errors='ignore')
result_df_04 = result_df_04.drop(index=['accuracy','micro avg','weighted avg'],errors='ignore')

result_df_01 = result_df_01.rename(index={"macro avg": "all"})
result_df_02 = result_df_02.rename(index={"macro avg": "all"})
result_df_03 = result_df_03.rename(index={"macro avg": "all"})
result_df_04 = result_df_04.rename(index={"macro avg": "all"})

# ✅ 1) make index name consistent
result_df_01.index.name = "pattern_class"
result_df_02.index.name = "pattern_class"
result_df_03.index.name = "pattern_class"
result_df_04.index.name = "pattern_class"

# ✅ 2) convert index -> column (so you can select it)
result_df_01 = result_df_01.reset_index()
result_df_02 = result_df_02.reset_index()
result_df_03 = result_df_03.reset_index()
result_df_04 = result_df_04.reset_index()


# ✅ 3) add step column
result_df_01["step"] = "1"
result_df_02["step"] = "2"
result_df_03["step"] = "3"
result_df_04["step"] = "4"

# # ✅ 4) keep only needed columns
cols = ["step", "pattern_class", "precision", "recall", "f1-score"]

result_df_01 = result_df_01[cols]
result_df_02 = result_df_02[cols]
result_df_03 = result_df_03[cols]
result_df_04 = result_df_04[cols]

# ✅ (optional) combine all steps
final_df = pd.concat([result_df_01, result_df_02, result_df_03, result_df_04], ignore_index=True)
final_df.to_csv("../evolution/evolution_final_report.csv", index=False)